version: '3.4'

services:
  af1server1:
    image: af1server1
    build:
      context: server
      dockerfile: ./.devcontainer/Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
