version: "3.9"
services:
  iot-1-server-1:
    container_name: iot-1-server-1
    build:
      context: ./server
      dockerfile: .devcontainer/Dockerfile
    ports:
      - "3021:3021"
    volumes:
      # This is where VS Code should expect to find your project's source code and the value of "workspaceFolder" in .devcontainer/devcontainer.json
      - ./server:/workspace
    command: /bin/sh -c "while sleep 1000; do :; done"
  iot-1-web-1:
    container_name: iot-1-web-1
    build:
      context: ./web
      dockerfile: .devcontainer/Dockerfile
    ports:
      - "3020:3020"
    volumes:
      - ./web:/workspace
    command: /bin/sh -c "while sleep 1000; do :; done"
  iot-1-lights-1:
    container_name: iot-1-lights-1
    build:
      context: ./firmware/lights
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ./firmware/lights:/workspace
    command: /bin/sh -c "while sleep 1000; do :; done"
