#ifndef STATE_H_
#define STATE_H_

enum custom_states
{
  STATE_HOME = 0,
  STATE_PATTERN_TWINKLEFOX,
  STATE_PATTERN_NOISEPLUSPALETTE,
  STATE_PATTERN_NOISE
};

enum custom_types
{
  TYPE_MQTT_SUBSCRIBE = 0,
  TYPE_MQTT_UNSUBSCRIBE,
  TYPE_MQTT_PAYLOAD,
};

#endif // STATE_H_